services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    ports:
      - '80:80'
    depends_on:
      - database
    entrypoint: ["python3", "/app/server.py"]
  database:
    build: ./database
    hostname: cassandra
    volumes: 
      - database:/bitnami
    ports:
      - '9042:9042'
volumes:
  database:
